# Jekyll Site Build Settings
# THIS FILE SHOULD RARELY BE EDITED

title: "Pathway"
baseurl: "/working-build/" # the subpath of your site, e.g. /blog/
url: "https://pathway.lds.org/" # the base hostname & protocol for your site

destination: "../working-build"

#demo-login-info
demoStudent: "Patty Pathway"
studentID: "123456789"


# Build settings
markdown: kramdown
